### PR TITLE
#5635 Add Config.DryRunMigration to prevent actually changing the schema when doing AutoMigrate()

### PR DESCRIPTION
**Pull request by googollee**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

Add a flag `Config.DryRunMigration` to let AutoMigrate() return an error before changing the schema.

### User Case Description

See #5635.

### CODE REVIEW

**Comment by googollee** [comment]
postgres tests failed.

```
2022/08/24 15:36:20 /home/runner/go/pkg/mod/gorm.io/driver/postgres@v1.3.9/migrator.go:140 ERROR: multiple default values specified for column "id" of table "posts" (SQLSTATE 42601)
[0.316ms] [rows:0] CREATE TABLE "posts" ("id" smallserial DEFAULT uuid_generate_v4(),"title" text,PRIMARY KEY ("id"))

2022/08/24 15:36:20 /home/runner/work/gorm/gorm/tests/postgres_test.go:97 ERROR: relation "posts" does not exist (SQLSTATE 42P01)
[0.662ms] [rows:0] INSERT INTO "posts" ("title") VALUES ('Hello World') RETURNING "id"
--- FAIL: TestMany2ManyWithDefaultValueUUID (0.01s)
    postgres_test.go:98: Failed, got error: ERROR: relation "posts" does not exist (SQLSTATE 42P01)
```

I don't think I touched that part.

**Comment by googollee** [comment]
That failure should be fixed by https://github.com/go-gorm/gorm/pull/5620.

**Comment by googollee** [comment]
This pr doesn't work properly. Closed.
